Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-18.04"

  config.vm.define :db do |db_config|
    db_config.vm.network "private_network", ip: "192.168.50.11"
    db_config.vm.hostname = 'db'
    db_config.vm.provider :virtualbox do |vb|
      vb.name = "db"
    end

    db_config.vm.provision "ansible" do |ansible|
			ansible.playbook = "playbooks/db.yml"
		end
    
	end

  config.vm.define :web do |web_config|
    web_config.vm.network "private_network", ip: "192.168.50.10"
    web_config.vm.hostname = 'web'
    web_config.vm.provider :virtualbox do |vb|
      vb.name = "web"
    end
    end
 
end